terraform {
  required_version = ">= 1.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }
}

# ── Data Source: read a pre-existing local file ──────────────────────────────
# BEFORE applying: run  echo '{"db_host":"db.example.com","db_port":5432}' > existing_config.json
data "local_file" "existing_config" {
  filename = "${path.module}/existing_config.json"
}

locals {
  # Parse the JSON content from the data source
  config     = jsondecode(data.local_file.existing_config.content)
  db_host    = local.config["db_host"]
  db_port    = local.config["db_port"]
}

# ── Resource that USES the data source ───────────────────────────────────────
resource "local_file" "app_config" {
  filename = "${path.module}/app_config.txt"
  content  = <<-EOT
    # Generated by Terraform — reads from pre-existing config
    DATABASE_HOST = ${local.db_host}
    DATABASE_PORT = ${local.db_port}
  EOT
}

# ── Data Source: http ─────────────────────────────────────────────────────────
data "http" "my_ip" {
  count = var.fetch_ip ? 1 : 0
  url   = "https://checkip.amazonaws.com"
}

# ── Outputs ───────────────────────────────────────────────────────────────────
output "db_host" {
  value = local.db_host
}

output "db_port" {
  value = local.db_port
}

output "raw_config_content" {
  value = data.local_file.existing_config.content
}

output "my_public_ip" {
  value = var.fetch_ip ? chomp(data.http.my_ip[0].response_body) : "fetch_ip is false"
}
