terraform {
  required_version = ">= 1.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

# ── Calling a LOCAL module (simulates the registry consumption pattern) ───────
# In production you'd use:
#   source  = "terraform-aws-modules/vpc/aws"
#   version = "~> 5.0"
# Here we use a local path so no cloud credentials are needed.

module "servers" {
  source = "./modules/server"

  for_each = var.servers

  name        = each.key
  role        = each.value.role
  environment = var.environment
  instance_size = each.value.size
}

# ── Using module outputs ───────────────────────────────────────────────────────
resource "local_file" "inventory" {
  filename = "${path.module}/inventory.txt"
  content  = <<-EOT
    # Server Inventory — generated by Terraform
    # Environment: ${var.environment}
    %{ for name, server in module.servers ~}
    ${name}:
      id:   ${server.server_id}
      role: ${server.role}
      size: ${server.instance_size}
    %{ endfor ~}
  EOT
}

output "server_ids" {
  value = { for k, v in module.servers : k => v.server_id }
}

output "server_summaries" {
  value = { for k, v in module.servers : k => v.summary }
}

output "inventory_file" {
  value = local_file.inventory.filename
}
